dierendeterminatie:
  dierendeterminatie.cloud.naturalis.nl:
    serveraliases: '*.cloud.naturalis.nl'
    docroot: /var/www/dierendeterminatie
    port: 80
    ssl: no
    serveradmin: bestaatniet@naturalis.nl
dierendeterminatie::backmeup: true
dierendeterminatie::backuphour: 2
dierendeterminatie::backupminute: 2
dierendeterminatie::backupdir: '/tmp/backups'
dierendeterminatie::autorestore: true
dierendeterminatie::restoreversion: 'latest'
dierendeterminatie::dest_id: 'provider_id'
dierendeterminatie::dest_key: 'provider_key'
dierendeterminatie::coderepo: 'http://dieren-code.googlecode.com/svn/trunk/'
dierendeterminatie::repotype: 'svn'
dierendeterminatie::coderoot: '/var/www/dierendeterminatie'

mysql::config::default_engine: myisam

monophylizer:
  monophylizer.cloud.naturalis.nl:
    serveraliases: '*.cloud.naturalis.nl'
    docroot: /var/www/monophylizer
    port: 80
    ssl: no
    serveradmin: bestaatniet@naturalis.nl
    options: +FollowSymLinks +ExecCGI

monophylizer::config::repo: https://github.com/ncbnaturalis/monophylizer.git

singleton_resource_package:
  parameters:
    ensure: present

puppetci::readonly: true

ntp::servers: 
  - 0.nl.pool.ntp.org
  - 1.nl.pool.ntp.org
  - 2.nl.pool.ntp.org
  - 3.nl.pool.ntp.org

baseusers:
  atze.devries:
   comment: "Atze"
   shell: "/bin/zsh"
   ssh_key: 
    type: "ssh-rsa"
    comment: "atze@hal"
    key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQCsFrALqpPIB00Q9gNbG3U/6zIzdG2ds1OfueQASozze/owocvRyjPL8FUfMzYr6TeU06MbBd6gdGMEa1bmWO2xL5exdBDWy9P30NtwCI2gzYZijOaIH5NBkQBMj0mYaPV/V72SrV7cQ1FMw02LBAq0ewnmcQ6aPNdimHb77X6BjzWOWl5KyGy8vWF0oCKKtG5IoCFNgLslEkj+C5lIyHbybDIp5hOr3DDKov4+jRjJBGlbFgSp0DmCD4iWShIdscKg8hFlmcm1iVEOffdEIY0wRezU+J1YOZAE2bVFDIuopOdzSDr/iX8x3bBpzrDKHaH8VcRPmLpm7ujv/2Vi+QbP"
  rudi.broekhuizen:
    comment: "Rudi"
    shell: "/bin/zsh"
    ssh_key:
      type: "ssh-rsa"
      comment: "rudi"
      key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQDeRrVuojExYBWgIV7UlLfYLvzGpW9hSzrjl9qJ7Kb3E/x+kq2ruma3LXlvMzFXoCKJMYvqvXUFj2Dzwh+iJ2bCyh5ilWgTMLvAwzRl1LdAV8IbDVYNZGCHCzXkyxLMAEdxXMHVYl6N/q+RBP+HQCySpwOjv86c5PgXoL4BOnxLy5TAoxSsfvxRcHT42ThYK1C/R5QC8UoBdpJ1RBhQRjBJPMWp9zRyOafNwE7Iti15gKHp04bn9UGqHRTA1ul+Q6YEFzjoqUxe4VCHObM6BS/DpD++TPMXjzU+aeJ8tkxhmYkGRKYJx/KK3uaKPv+/EkODePvwTVshiQ8v9qOXx0YJ"
